import './App.css'
import { Organ_grid } from './components/Organ_grid'
import { type DNA } from './interfaces/dna'

function App() {
        let DNAs:DNA[] = [
                {
                layers:4,
                branches:2,
                del_branches:0,
                angles:4,
                del_angles:0,
                length:20,
                del_length:-7,
        },
        {
                layers:4,
                branches:3,
                del_branches:0,
                angles:4,
                del_angles:0,
                length:20,
                del_length:-7,
        },
                {
                layers:4,
                branches:2,
                del_branches:0,
                angles:4,
                del_angles:0,
                length:20,
                del_length:-6,
        },
                {
                layers:4,
                branches:2,
                del_branches:0,
                angles:4,
                del_angles:0,
                length:20,
                del_length:-7,
        },
                {
                layers:4,
                branches:2,
                del_branches:0,
                angles:4,
                del_angles:0,
                length:20,
                del_length:-7,
        },
                {
                layers:4,
                branches:2,
                del_branches:0,
                angles:4,
                del_angles:0,
                length:20,
                del_length:-7,
        },
                {
                layers:4,
                branches:2,
                del_branches:0,
                angles:4,
                del_angles:0,
                length:20,
                del_length:-7,
        },
                {
                layers:4,
                branches:2,
                del_branches:0,
                angles:4,
                del_angles:0,
                length:20,
                del_length:-7,
        },
                {
                layers:4,
                branches:2,
                del_branches:0,
                angles:4,
                del_angles:0,
                length:20,
                del_length:-7,
        },
                {
                layers:4,
                branches:2,
                del_branches:0,
                angles:4,
                del_angles:0,
                length:20,
                del_length:-7,
        },
                {
                layers:4,
                branches:2,
                del_branches:0,
                angles:4,
                del_angles:0,
                length:20,
                del_length:-7,
        },
                {
                layers:4,
                branches:2,
                del_branches:0,
                angles:4,
                del_angles:0,
                length:20,
                del_length:-7,
        },
                {
                layers:4,
                branches:2,
                del_branches:0,
                angles:4,
                del_angles:0,
                length:20,
                del_length:-7,
        },
                {
                layers:4,
                branches:2,
                del_branches:0,
                angles:4,
                del_angles:0,
                length:20,
                del_length:-7,
        },
        ]
        return (
                <>
                        <Organ_grid DNAs={DNAs}/>
                </>
        )
}

export default App
